### ISSUE TITLE
请问下代码和论文中介绍的版本是一样的吗？

### ISSUE THREAD

**Issue by Zh-cy** [linjian93/pytorch-deepvo#10]
首先非常感谢您的开源代码，最近正在学习，可是在研究中发现代码和论文中所说还是有些出入，请问这方面是以论文为主还是代码为主？

**Comment by linjianz** [comment]
@Zh-cy 
1. 代码基本和论文一至，实验结果都是可复现的，只不过论文中展示的是某次调参效果最好结果。
2. 关于论文和代码，我的建议是，先理解论文中的方法，代码只是一个辅助你实现想法的工具，完全可以自己从头写一个出来。现在 DeepVO 应该有更多前沿工作，可以跟进一下，不局限我这里的方法。

**Comment by Zh-cy** [comment]
多谢回复！
