### ISSUE TITLE
lstm输入维度问题

### ISSUE THREAD

**Issue by LiuWheel** [linjian93/pytorch-deepvo#11]
pytorch官方doc中给出的lstm输入为：seq_len, batch, input_size，在此项目中的输入为batch,seq_len,input_size???

**Comment by linjianz** [comment]
@LiuWheel  时间有些久远了，当时的版本里，lstm 是有一个参数 `batch_first` 来控制前两个维度的顺序的。

**Comment by LiuWheel** [comment]
在这个版本中有吗？看了一下CNN-LSTM模型，没有发现。

**Comment by linjianz** [comment]
> 在这个版本中有吗？看了一下CNN-LSTM模型，没有发现。

@LiuWheel 不好意思，这个项目已经不维护了，难免很多bug，只用做参考。建议自己重构代码，deepvo的思路也不复杂。
