### ISSUE TITLE
loss返回值

### ISSUE THREAD

**Issue by Dream-Runner-Yu** [linjian93/pytorch-deepvo#13]
Traceback (most recent call last):
  File "main.py", line 426, in <module>
    main()
  File "main.py", line 354, in main
    loss_func=loss_func, optimizer=optimizer)
  File "main.py", line 175, in run_batch_2
    loss1_mean.append(loss1.data[0])
IndexError: invalid index of a 0-dim tensor. Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number

**Comment by student-petercai** [comment]
I encountered the same issue as well, then I downgraded the pytorch version to 0.4.1 and solved it

**Comment by 1212kyky** [comment]
However, pytorch 0.4.1 does not have a dataloader, and there is such an error: modulenotfounderror: no module named 'torch utils. data' @student-petercai
