### ISSUE TITLE
cnn-lstm训练了10轮效果不好啊

### ISSUE THREAD

**Issue by Ironbrotherstyle** [linjian93/pytorch-deepvo#3]
师兄你好，因为时间要求太长，我只训练了10轮（默认100），发现结果很不好。loss是这样
![screenshot from 2019-02-25 11-03-45](https://user-images.githubusercontent.com/28485294/53311765-26bf8100-38ed-11e9-9095-29d18d264276.png)
测试的结果是这样：

![0](https://user-images.githubusercontent.com/28485294/53311837-70a86700-38ed-11e9-9f28-e14f9baecb01.png)

![1](https://user-images.githubusercontent.com/28485294/53311838-73a35780-38ed-11e9-8582-9b152afabcbd.png)

请问是我训练的epoch太少了还是说其他参数啥的出了问题？

**Comment by 1131034310** [comment]
你好，我也存在这样的问题，训练了50轮，Loss完全没有收敛。
loss的结果：
![_20190225112822](https://user-images.githubusercontent.com/29299433/53317263-ef110300-3905-11e9-8ae7-d02da53a7c09.jpg)
测试的结果：
![5-epoch-50](https://user-images.githubusercontent.com/29299433/53318271-ae1aed80-3909-11e9-80f6-a1223f768840.png)
![9-epoch-50](https://user-images.githubusercontent.com/29299433/53318278-b4a96500-3909-11e9-9e35-d69d00eac5a1.png)
想请教作者的论文结果是如何得到的，如何实现收敛得出结果？

**Comment by Ironbrotherstyle** [comment]
> 你好，我也存在这样的问题，训练了50轮，Loss完全没有收敛。
> loss的结果：
> ![_20190225112822](https://user-images.githubusercontent.com/29299433/53317263-ef110300-3905-11e9-8ae7-d02da53a7c09.jpg)
> 测试的结果：
> ![5-epoch-50](https://user-images.githubusercontent.com/29299433/53318271-ae1aed80-3909-11e9-80f6-a1223f768840.png)
> ![9-epoch-50](https://user-images.githubusercontent.com/29299433/53318278-b4a96500-3909-11e9-9e35-d69d00eac5a1.png)
> 想请教作者的论文结果是如何得到的，如何实现收敛得出结果？

同学你好，有兴趣加联系方式细聊吗？ qq：1498944745

**Comment by linjianz** [comment]
cnn-lstm train from scratch 是可以收敛的，我记得是要训练多个 epoch 之后才会看到效果。如果短期内无法收敛，可以先在 cnn-vo 训练好的模型的基础上做 fine-tuning，可以缩短收敛时间的，同时检查下 lstm 部分的代码是不是有问题。我记得是要改下 lstm 的激活函数，具体细节可以看看我的毕业论文。

**Comment by Ironbrotherstyle** [comment]
好的 谢谢 我再试试 训练太慢了 四块1080ti也很慢咋办




    


在2019年02月25日 23:31，JiAnge 写道： cnn-lstm train from scratch 是可以收敛的，我记得是要训练多个 epoch 之后才会看到效果。如果短期内无法收敛，可以先在 cnn-vo 训练好的模型的基础上做 fine-tuning，可以缩短收敛时间的，同时检查下 lstm 部分的代码是不是有问题。我记得是要改下 lstm 的激活函数，具体细节可以看看我的毕业论文。

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/linjian93/pytorch-deepvo","title":"linjian93/pytorch-deepvo","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/linjian93/pytorch-deepvo"}},"updates":{"snippets":[{"icon":"PERSON","message":"@linjian93 in #3: cnn-lstm train from scratch 是可以收敛的，我记得是要训练多个 epoch 之后才会看到效果。如果短期内无法收敛，可以先在 cnn-vo 训练好的模型的基础上做 fine-tuning，可以缩短收敛时间的，同时检查下 lstm 部分的代码是不是有问题。我记得是要改下 lstm 的激活函数，具体细节可以看看我的毕业论文。"}],"action":{"name":"View Issue","url":"https://github.com/linjian93/pytorch-deepvo/issues/3#issuecomment-467055647"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/linjian93/pytorch-deepvo/issues/3#issuecomment-467055647",
"url": "https://github.com/linjian93/pytorch-deepvo/issues/3#issuecomment-467055647",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by AdamAsh2019** [comment]
确实要训练100epoch左右。。。。。我用了8块titan xp训练了9小时
