### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by ghost** [linjian93/pytorch-deepvo#5]
训练的时候python3 main.py --server=6499 --net_architecture=cnn --phase=Train --resume=No --net_name=cnn-vo --dir0=20180109 --gpu=1 提示No such file or directory: '/media/jiange/095df4a3-d72c-43d9-bfbd-e78651afba19/model-jiange/pytorch-deepvo/cnn-vo'，这该怎么办呢

**Comment by linjianz** [comment]
@jokezhao 数据、模型的路径在`main.py`的最开始都定义死了，需要改成你自己本地或者服务器上的路径。
