### ISSUE TITLE
cnn-lstm-vo训练loss疑问

### ISSUE THREAD

**Issue by AdamAsh2019** [linjian93/pytorch-deepvo#7]
你好，非常感谢您发布的工程，前几天你们刘勇老师也来我们学校进行交流，十分受用。昨天我进行了CNN-LSTM-VO的训练发现loss的数量级和你论文中提到的不一样。CNN-VO的loss和论文的一样是个位数，而CNN-LSTM-VO的却成了百位数（终端窗口中实时显示的）。。参数我是用CNN-VO训练100epoch的，即使是没用预训练的参数loss也是在百位数。请问这是正常情况吗？是不是因为有image pairs的原因？

**Comment by linjianz** [comment]
你好，你出现的 CNN-LSTM-VO 的误差在百位数的现象，很可能不正常。如果误差很大但是迭代次数增加后会收敛，那可能是误差计算那里没有求平均或者其他原因导致的；如果误差一直很大而且不收敛，那可能需要检查 LSTM 那块的代码。我论文里的 CNN-LSTM-VO，如果 train from scratch，也是可以收敛到比较好的效果；如果采用 CNN-VO 的预训练参数，则收敛速度会更快。
