### ISSUE TITLE
一些小问题与疑问 探讨

### ISSUE THREAD

**Issue by fangxu622** [linjian93/pytorch-deepvo#8]
1 选择从头训练的时候，出现 re 模块的 error，我将sample 默认值 从None,改为“” 解决了。暂时还没来集仔细研究代码，不知道这对后续代码运行有什么影响。

```
(torch1.1) fangxu@light-Precision-Tower-7910:/media/fangxu/seagate/Linux-Proj/deep-slam/pytorch-deepvo$ python main.py --server=6499 --net_architecture=cnn --phase=Train --resume=No --net_name=cnn-vo --dir0=20191029 --gpu=1 
/media/fangxu/seagate/Linux-Proj/deep-slam/pytorch-deepvo/net/cnn.py:54: UserWarning: nn.init.xavier_normal is now deprecated in favor of nn.init.xavier_normal_.
  xavier_normal(m.weight.data)

========================================
Phase: Train
Net architecture: cnn
Initialize from scratch
========================================
Traceback (most recent call last):
  File "main.py", line 426, in <module>
    main()
  File "main.py", line 376, in main
    data_set_v = KITTIDataSet(dir_data=dir_data, dir_label=dir_label, phase='Valid')
  File "/media/fangxu/seagate/Linux-Proj/deep-slam/pytorch-deepvo/dataset/kitti.py", line 22, in __init__
    self.l1, self.l2, self.label = self.load_data()
  File "/media/fangxu/seagate/Linux-Proj/deep-slam/pytorch-deepvo/dataset/kitti.py", line 32, in load_data
    samples_list = list(filter(None, re.split('[, ]', self.samples)))  # 提取字符串，并去掉空格
  File "/home/fangxu/anaconda3/envs/torch1.1/lib/python3.6/re.py", line 212, in split
    return _compile(pattern, flags).split(string, maxsplit)
TypeError: expected string or bytes-like object

```
2 在 main_generate_data.py 中，
generate_xyz_euler_relative(0) 这个函数的参数之不同有什么影响吗？这个参数值好像是不是 起始点把

3 成功运行之后，使用命令
tensorborad --logdir ./log 进行可视化，loss值好像不能实时更新，不知道是pytorch 的问题还是 ？

最近有一个在实现一个深度学习的VIO 框架，可能参考作者一些代码，希望能在这个issue 下面与作者探讨i运行该代码的小问题。避免走些弯路  ，感激不仅啦

**Comment by czar10** [comment]
@fangxu622 
1.  self.samples = str(samples) 可以解决。
2.  那个0是指生成interval为0的标签，你改成1,2,3就对应interval 123
3. 估计你的tensorboard --logdir 路径不对，logdir要进到你具体summarywriter的那个文件夹。

**Comment by linjianz** [comment]
@fangxu622 首先感谢你能关注到这个小项目，我开源代码后就没继续维护了，DeepVO 这个方向也没有继续跟进。你的疑问 @czar10 回答得很具体了，感谢。代码开源时并没有考虑太多平台的因素，难免在不同中运行会有各种bug，同时代码也有很多地方可以继续优化。祝好。

**Comment by fangxu622** [comment]
@linjian93 @czar10  嗯嗯，谢谢回复，正在研究中。望后面可以再交流沟通

**Comment by fangxu622** [comment]
@linjian93 @czar10  对文章使用 绝对 位姿 SE3 与 求相对 位姿SE3 的公式没有疑问，但是文章的实现函数 使用的是 r1.I *r2 。


```
t1 = mat(np.row_stack((np.reshape(t_12d[j, :], (3, 4)), [0, 0, 0, 1])))
t2 = mat(np.row_stack((np.reshape(t_12d[j+it+1, :], (3, 4)), [0, 0, 0, 1])))
t12 = t1.I * t2
ret[j, 0: 3] = [t12[0, 3], t12[1, 3], t12[2, 3]]
```

 这样的实现好像不对，但我不确认，因为最新的pytorch3d  

里面有这个转换函数，我对比了以下，得到的相对位姿的结果不同

**Comment by fangxu622** [comment]
我想问一下，其他baseline 方法的轨迹是如何拿到的··？@linjian93 @czar10

**Comment by linjianz** [comment]
> 我想问一下，其他baseline 方法的轨迹是如何拿到的··？@linjian93 @czar10

@fangxu622 [KITTI 官网](http://www.cvlibs.net/datasets/kitti/eval_odometry.php) 有提供几种 baseline 的代码，可以直接跑出结果。
