### ISSUE TITLE
各种结果之间的对比

### ISSUE THREAD

**Issue by Royaler** [linjian93/pytorch-deepvo#9]
你好，我该如何在一张图里面来对比不同算法得到的效果呢，还有就是如何画出与VISO-S和VISO-M的对比图呢，我看evaluation里面没有具体函数的实现。

**Comment by Royaler** [comment]
from utils.my_color import color_line as col
from utils.plot_misc import plot_evaluation, plot_trajectory
这两个函数没有，还有就是如何获得loss的json数据呢 @linjian93

**Comment by linjianz** [comment]
@Royaler 可以参考 KITTI 官网 http://www.cvlibs.net/datasets/kitti/eval_odometry.php，里面的development kit 提供了一些处理结果的函数，应该能满足你的需求。my_color 和 plot_misc 这两个函数时间有点久忘了放哪了。loss.json 是训练过程中实时保存的数据。

**Comment by Royaler** [comment]
@linjian93 很高兴你能解答我，我还有一个疑问就是我想用viso中的两个算法来跑结果并与自己的进行对比，我需要亲自跑一遍这个算法吗
